#!/usr/bin/env bash
#
# aur:remove - uninstall aur packages

info() {
	printf "\e[0;34m:: \e[1;37m%s\e[0m\n" "$@"
}

cd /tmp

for pkg in "$@"
do
	if ! pacman -Qi "${pkg}"
	then
		info "pacman exited with error: skipping ${pkg}."
		continue
	fi

	# remove package with pacman
	info "removing package ${pkg}"
	pacman -R "${pkg}"
done
