#!/usr/bin/env bash
#
# aur:upgrade - upgrade all outdated aur packages

info() {
	printf "\e[0;34m:: \e[1;37m%s\e[0m\n" "$@"
}

OIFS="${IFS}"
ODIR=$(pwd)
SDIR="$( cd "$(dirname "$0")" ; pwd -P )"
cd /tmp

info "retrieving list of outdated apps"

IFS="
"
for line in `${SDIR}/lib/out-of-date`
do
	IFS=' ' read -ra DATA <<< "$line"
	PKG="${DATA[0]}"
	OVR="${DATA[1]}"
	SVR="${DATA[2]}"
	
	# upgrade the package
	info "upgrading '${PKG}' from ${OVR} to ${NVR}"
	rm -f "${PKG}.tar.gz"

	# download package with curl
	info "downloading ${PKG} with curl"
	curl -L -O "https://aur.archlinux.org/cgit/aur.git/snapshot/${PKG}.tar.gz"

	# extract tarball
	info "extracting '${PKG}' tarball"
	tar -xvf "${PKG}.tar.gz"

	# move into directory
        cd "${PKG}"

	# run makepkg
	info "running 'makepkg -sir'"
        makepkg -sir

	rm -rf "./${PKG}"
	rm -f "${PKG}.tar.gz"

done

IFS="${OIFS}"
cd "${ODIR}"
