#!/usr/bin/env bash
#
# aur:install - simple aur helper


info() {
	printf "\e[0;34m:: \e[1;37m%s\e[0m\n" "$@"
}

# only idiots run aur helpers as root
if [[ $EUID -eq 0 ]]; then
	printf "ERROR: this must not be run as root!!!\n"
	exit 1
fi

cd /tmp

for pkg in "$@"
do
	# check if package is official repos
	if pacman -Ssq | sort | grep "^${pkg}\$" > /dev/null; then
		info "installing '${pkg}' with pacman"
		sudo pacman -S "${pkg}"
		exit 0
	fi

	rm -f "${pkg}.tar.gz"

	# download package with curl
	info "downloading ${pkg} with curl"
	curl -L -O "https://aur.archlinux.org/cgit/aur.git/snapshot/${pkg}.tar.gz"

	# extract tarball
	info "extracting '${pkg}' tarball"
	tar -xvf "${pkg}.tar.gz"

	# move into directory
        cd "${pkg}"

	# run makepkg
	info "running 'makepkg -sir'"
        makepkg -sir
done
