#!/usr/bin/env bash
#
# aur:upgrade - upgrade all outdated aur packages

info() {
	printf "\e[0;34m:: \e[1;37m%s\e[0m\n" "$@"
}

OIFS="${IFS}"
ODIR=$(pwd)
SDIR="$( cd "$(dirname "$0")" ; pwd -P )"
cd /tmp

info "retrieving list of outdated apps"

declare -a pkgs=()
IFS="
"
for line in `${SDIR}/../lib/out-of-date`
do
	pkgs+=("${line}")
done

# list all oudated packages
if [[ ${#pkgs[@]} -eq 0 ]]; then
	info "there is nothing to do"
	exit 0
else
	info "upgrade the following packages: "
fi

IFS="${OIFS}"
for item in "${pkgs[@]}"
do
	IFS=' ' read -ra DATA <<< "$item"
	PKG="${DATA[0]}"
	printf "\t\e[1;34m•\e[1;37m $PKG\n\e[0m"
done

IFS="${OIFS}"
cd "${ODIR}"